repos:
    -  repo:  https://github.com/antonbabenko/pre-commit-terraform
        rev:  v1.88.0
        hooks:
            -  id:  terraform_fmt
            -  id:  terraform_validate

    -  repo:  https://github.com/pre-commit/mirrors-prettier
        rev:  v3.2.5
        hooks:
            -  id:  prettier
                files:  "\\.(json|md|yml|yaml)$"
